name: Build Vue
on:
  push:
    branches:
      - source  # Utilisez une branche "source" pour votre code source

permissions:
  contents: write

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: |
          cd portfolio
          npm install
      - name: Build
        run: |
          cd portfolio
          npm run build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: main  # Déployez sur main au lieu de gh-pages
          folder: portfolio/dist